# Generated by Django 5.2.5 on 2025-09-06 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("ST", "Stock"),
                            ("BO", "Bond"),
                            ("MF", "Mutual Fund"),
                            ("ET", "ETF"),
                            ("CR", "Cryptocurrency"),
                            ("RE", "Real Estate"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("symbol", models.CharField(blank=True, max_length=10)),
                (
                    "initial_investment",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("purchase_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
