# Generated by Django 5.2.5 on 2025-09-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
