# Generated by Django 5.2.5 on 2025-09-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(default="📂", max_length=10),
        ),
    ]
